# Generated by Django 4.2 on 2023-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0002_prettynum_alter_userinfo_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='mobiles',
            new_name='mobile',
        ),
    ]
