# Generated by Django 4.2 on 2023-04-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0003_rename_mobiles_prettynum_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
