# Generated by Django 4.2 on 2023-05-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详情')),
                ('level', models.SmallIntegerField(choices=[(1, '日常'), (2, '重要'), (3, '紧急')], default=1, verbose_name='类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_web.admin', verbose_name='负责人')),
            ],
        ),
    ]
