# Generated by Django 4.2 on 2023-05-17 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0006_rename_user_news_admin_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_web.admin', verbose_name='用户'),
        ),
    ]
